### ISSUE TITLE
proguard rules

### ISSUE THREAD

**Issue by RicardoBelchior** [konradrenner/kore-javamail#3]
hi, 

do you need/have any pre-configured proguard rules for this library? 

building a release complains with the following warning:

```
Warning: korex.activation.CommandInfo: can't find referenced class java.beans.Beans
```

best regards,
ricardo

**Comment by konradrenner** [comment]
Hi! I don't exactly know what you mean. This project is open source, so using obfuscating the code is not necessary I think?

**Comment by RicardoBelchior** [comment]
well proguard not only obfuscates but also removes unused code in the app. Proguard rules specify any class/method that should be keep after compilation. 

http://developer.android.com/tools/help/proguard.html#configuring

related question on stackoverflow 
http://stackoverflow.com/q/5434699/1383284

anyhow, no worries. i was just checking

**Comment by konradrenner** [comment]
OK, I understand. If you can provide rules, that would be awesome ;-)
