### ISSUE TITLE
How to handle IMAPS

### ISSUE THREAD

**Issue by ghost** [konradrenner/kore-javamail#4]
Hello, 

I'm trying to use this library to connect to an email account using IMAPS. I'm getting this error : 
korex.mail.MessagingException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.;

Here's my code : 
props.setProperty("mail.transport.protocol", "imaps");
 props.setProperty("mail.imaps.host", account.getImapServer());
 props.put("mail.imaps.auth", "true");
 props.put("mail.imaps.port", account.getImapPort()); // this is 993
 props.put("mail.imaps.socketFactory.port", account.getImapPort()); // also 993
 props.put("mail.imaps.socketFactory.class",
                "javax.net.ssl.SSLSocketFactory");
 props.put("mail.imaps.socketFactory.fallback", "true");
 props.setProperty("mail.imaps.quitwait", "false");
  Session session = Session.getDefaultInstance(props);

```
    ArrayList<Message> messages = null;
    String destinationDirectory = account.getDownloadLocation();

    try {
        // connects to the message store
        Store store = session.getStore("imaps");
        store.connect(account.getImapServer(), account.getAddress(), account.getPassword());


        .......
   } catch(...){..}
```

thank your help.

**Comment by konradrenner** [comment]
Hi, do you want to connect to a server with a self signed certificate?

**Comment by konradrenner** [comment]
You can find an example here: https://github.com/konradrenner/kolabnotes-java/blob/master/src/main/java/org/kore/kolab/notes/imap/ImapNotesRepository.java
